language: python

env:
  global:
    # skip 2.7, 3.4 and 3.5: for now, only build for 3.6
    - CIBW_SKIP: "cp27-* cp34-* cp35-*"
    - CIBW_BEFORE_BUILD: "{pip} install -r requirements-dev.txt"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

script:
  - $PIP install cibuildwheel==0.7.1
  - cibuildwheel --output-dir wheelhouse
