language: python

env:
  global:
    # skip 2.7, 3.4 and 3.5: for now, only build for 3.6
    - CIBW_SKIP="cp27-* cp33-* cp34-* cp35-*"
    - CIBW_BEFORE_BUILD="{pip} install -r requirements-dev.txt"

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

install:
  # XXX not sure why this is needed, given that CIBW_BEFORE_BUILD is defined
  # already. Probably because setup.py imports skbuild, and cibuildwheel
  # imports it somehow?
  - $PIP install -e git+https://github.com/scikit-build/scikit-build.git#egg=scikit-build

script:
  - $PIP install cibuildwheel==0.7.1
  - cibuildwheel --output-dir wheelhouse
