environment:
  global:
    # skip 2.7, 3.4 and 3.5: for now, only build for 3.6
    CIBW_SKIP: "cp27-* cp33-* cp34-* cp35-*"
    CIBW_BEFORE_BUILD: "{pip} install -r requirements-dev.txt"

install:
  - python -m pip install --upgrade pip
  - pip install -r requirements-dev.txt

build_script:
  - pip install cibuildwheel==0.7.1
  - cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
